// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: bookkeeper-go/proto/ledger_data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LedgerData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists      bool   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Fenced      bool   `protobuf:"varint,2,opt,name=fenced,proto3" json:"fenced,omitempty"`
	MasterKey   []byte `protobuf:"bytes,3,opt,name=masterKey,proto3" json:"masterKey,omitempty"`
	ExplicitLac []byte `protobuf:"bytes,4,opt,name=explicitLac,proto3" json:"explicitLac,omitempty"`
	Limbo       bool   `protobuf:"varint,5,opt,name=limbo,proto3" json:"limbo,omitempty"`
}

func (x *LedgerData) Reset() {
	*x = LedgerData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookkeeper_go_proto_ledger_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LedgerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerData) ProtoMessage() {}

func (x *LedgerData) ProtoReflect() protoreflect.Message {
	mi := &file_bookkeeper_go_proto_ledger_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerData.ProtoReflect.Descriptor instead.
func (*LedgerData) Descriptor() ([]byte, []int) {
	return file_bookkeeper_go_proto_ledger_data_proto_rawDescGZIP(), []int{0}
}

func (x *LedgerData) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *LedgerData) GetFenced() bool {
	if x != nil {
		return x.Fenced
	}
	return false
}

func (x *LedgerData) GetMasterKey() []byte {
	if x != nil {
		return x.MasterKey
	}
	return nil
}

func (x *LedgerData) GetExplicitLac() []byte {
	if x != nil {
		return x.ExplicitLac
	}
	return nil
}

func (x *LedgerData) GetLimbo() bool {
	if x != nil {
		return x.Limbo
	}
	return false
}

var File_bookkeeper_go_proto_ledger_data_proto protoreflect.FileDescriptor

var file_bookkeeper_go_proto_ledger_data_proto_rawDesc = []byte{
	0x0a, 0x25, 0x62, 0x6f, 0x6f, 0x6b, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x62, 0x6f, 0x6f, 0x6b, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x92, 0x01, 0x0a, 0x0a, 0x4c, 0x65, 0x64, 0x67, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x66, 0x65, 0x6e, 0x63, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x66,
	0x65, 0x6e, 0x63, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x4c,
	0x61, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x6c, 0x69, 0x63,
	0x69, 0x74, 0x4c, 0x61, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x62, 0x6f, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x62, 0x6f, 0x42, 0x15, 0x5a, 0x13, 0x62,
	0x6f, 0x6f, 0x6b, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bookkeeper_go_proto_ledger_data_proto_rawDescOnce sync.Once
	file_bookkeeper_go_proto_ledger_data_proto_rawDescData = file_bookkeeper_go_proto_ledger_data_proto_rawDesc
)

func file_bookkeeper_go_proto_ledger_data_proto_rawDescGZIP() []byte {
	file_bookkeeper_go_proto_ledger_data_proto_rawDescOnce.Do(func() {
		file_bookkeeper_go_proto_ledger_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_bookkeeper_go_proto_ledger_data_proto_rawDescData)
	})
	return file_bookkeeper_go_proto_ledger_data_proto_rawDescData
}

var file_bookkeeper_go_proto_ledger_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bookkeeper_go_proto_ledger_data_proto_goTypes = []interface{}{
	(*LedgerData)(nil), // 0: bookkeeper.protol.ledger_data.LedgerData
}
var file_bookkeeper_go_proto_ledger_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bookkeeper_go_proto_ledger_data_proto_init() }
func file_bookkeeper_go_proto_ledger_data_proto_init() {
	if File_bookkeeper_go_proto_ledger_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bookkeeper_go_proto_ledger_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LedgerData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bookkeeper_go_proto_ledger_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bookkeeper_go_proto_ledger_data_proto_goTypes,
		DependencyIndexes: file_bookkeeper_go_proto_ledger_data_proto_depIdxs,
		MessageInfos:      file_bookkeeper_go_proto_ledger_data_proto_msgTypes,
	}.Build()
	File_bookkeeper_go_proto_ledger_data_proto = out.File
	file_bookkeeper_go_proto_ledger_data_proto_rawDesc = nil
	file_bookkeeper_go_proto_ledger_data_proto_goTypes = nil
	file_bookkeeper_go_proto_ledger_data_proto_depIdxs = nil
}
